rivers=['Днестр','Енисей','Амазонка','Днепр','Волга','Саксаганка','Нил']
rivers.reverse()
print(rivers)
rivers.sort()
print(rivers)
rivers.sort(reverse=1)
print(rivers)
print(sorted(rivers, reverse=1))
print(sorted(rivers, reverse=1))
del(rivers[0])
print(rivers)
del_river=rivers.pop()
print(del_river)
print(rivers)
t=len(rivers)
print(rivers)
rivers[2]='Обь'
print(rivers)
rivers.append('Миссисипи')
print(rivers)
rivers.insert(0,'Янцзи')
print(rivers)
message=f"Такие реки у нас есть: {rivers[0],rivers[1],rivers[2],rivers[3],rivers[4],rivers[5],rivers[6]}"
print(message)
